USE [PortalTransparencia]
GO

-- ====================================================================================================
-- Autor: <Anderson Araújo>
-- Data de criação: <2023-10-15>
-- Data de atualização: <2023-10-15>
-- Descrição: <Script para criar a tabela de depara de cidades>
-- ====================================================================================================

DROP TABLE IF EXISTS [Depara].[CidadesAbreviadas]
CREATE TABLE [Depara].[CidadesAbreviadas] (
    [id] INT IDENTITY (1, 1) NOT NULL
,   [Cidade] VARCHAR (100) NOT NULL
,   [CidadeNormalizada] VARCHAR (100) NOT NULL
)

ALTER TABLE [Depara].[CidadesAbreviadas]
ADD CONSTRAINT [PK_CidadesAbreviadas] PRIMARY KEY CLUSTERED ([id] ASC)

ALTER TABLE [Depara].[CidadesAbreviadas]
ADD CONSTRAINT [UK_CidadesAbreviadas_Cidade] UNIQUE NONCLUSTERED ([Cidade] ASC)

INSERT INTO [Depara].[CidadesAbreviadas] (
    [Cidade]
,   [CidadeNormalizada]
)
VALUES
('S.PAULO', 'SÃO PAULO'),
('S.ANDRE', 'SANTO ANDRÉ'),
('S.BERNARDO DO CAMPO', 'SÃO BERNARDO DO CAMPO'),
('S.JOSE DOS CAMPOS', 'SÃO JOSÉ DOS CAMPOS'),
('S.VICENTE', 'SÃO VICENTE'),
('S.JOSE DO RIO PRETO', 'SÃO JOSÉ DO RIO PRETO'),
('S.CAETANO DO SUL', 'SÃO CAETANO DO SUL'),
('S.CARLOS', 'SÃO CARLOS'),
('S.SEBASTIAO', 'SÃO SEBASTIÃO'),
('S.BARBARA D OESTE', 'SANTA BÁRBARA D''OESTE'),
('S.ROQUE', 'SÃO ROQUE'),
('S.ISABEL', 'SANTA ISABEL'),
('S.JOAO DA BOA VISTA', 'SÃO JOÃO DA BOA VISTA'),
('S.CRUZ DO RIO PARDO', 'SANTA CRUZ DO RIO PARDO'),
('S.LOURENCO DA SERRA', 'SÃO LOURENÇO DA SERRA'),
('S.FE DO SUL', 'SANTA FÉ DO SUL'),
('S.JOAQUIM DA BARRA', 'SÃO JOAQUIM DA BARRA'),
('S.MANUEL', 'SÃO MANUEL'),
('S.JOSE DO RIO PARDO', 'SÃO JOSÉ DO RIO PARDO'),
('ESPIRITO STO. PINHAL', 'ESPÍRITO SANTO DO PINHAL'),
('S.PEDRO', 'SÃO PEDRO'),
('S.MIGUEL ARCANJO', 'SÃO MIGUEL ARCANJO'),
('S.ANTONIO DE POSSE', 'SANTO ANTÔNIO DE POSSE'),
('S.GERTRUDES', 'SANTA GERTRUDES'),
('S.RITA PASSA QUATRO', 'SANTA RITA DO PASSA QUATRO'),
('S.CRUZ DAS PALMEIRAS', 'SANTA CRUZ DAS PALMEIRAS'),
('S.ROSA DE VITERBO', 'SANTA ROSA DE VITERBO'),
('S.SIMAO', 'SÃO SIMÃO'),
('S.BRANCA', 'SANTA BRANCA'),
('S.ADELIA', 'SANTA ADÉLIA'),
('S.MARIA DA SERRA', 'SANTA MARIA DA SERRA'),
('S.ANASTACIO', 'SANTO ANASTÁCIO'),
('S.JOSE DA BELA VISTA', 'SÃO JOSÉ DA BELA VISTA'),
('S.SEBASTIAO DA GRAMA', 'SÃO SEBASTIÃO DA GRAMA'),
('S.ANTONIO DA ALEGRIA', 'SANTO ANTÔNIO DA ALEGRIA'),
('S.ERNESTINA', 'SANTA ERNESTINA'),
('S.LUCIA', 'SANTA LÚCIA'),
('S.LUIS DO PARAITINGA', 'SÃO LUÍS DO PARAITINGA'),
('S.BENTO DO SAPUCAI', 'SÃO BENTO DO SAPUCAÍ'),
('ESPIRITO S.DO TURVO', 'ESPÍRITO SANTO DO TURVO'),
('S.LUIZ DO PARAITINGA', 'SÃO LUÍS DO PARAITINGA'),
('S.ANTONIO DO JARDIM', 'SANTO ANTÔNIO DO JARDIM'),
('S.ANTONIO DE ARACANGUA', 'SANTO ANTÔNIO DE ARACANGUÁ'),
('S.ANTONIO DO PINHAL', 'SANTO ANTÔNIO DO PINHAL'),
('S.CRUZ DA CONCEICAO', 'SANTA CRUZ DA CONCEIÇÃO'),
('S.PEDRO DO TURVO', 'SÃO PEDRO DO TURVO'),
('S.CLARA D OESTE', 'SANTA CLARA D''OESTE'),
('S.CRUZ DA ESPERANCA', 'SANTA CRUZ DA ESPERANÇA'),
('S.ALBERTINA', 'SANTA ALBERTINA'),
('S.EXPEDITO', 'SANTO EXPEDITO'),
('S.FRANCISCO', 'SÃO FRANCISCO'),
('S.JOAO DE IRACEMA', 'SÃO JOÃO DE IRACEMA'),
('S.JOSE DO BARREIRO', 'SÃO JOSÉ DO BARREIRO'),
('S.JOAO DUAS PONTES', 'SÃO JOÃO DAS DUAS PONTES'),
('S.MERCEDES', 'SANTA MERCEDES'),
('S.SALETE', 'SANTA SALETE'),
('S.RITA D OESTE', 'SANTA RITA D''OESTE'),
('S.JOAO DO PAU D ALHO', 'SÃO JOÃO DO PAU D''ALHO'),
('CAMPOS NOVOS PAUL.', 'CAMPOS NOVOS PAULISTA')
